# Generated by Django 3.2.5 on 2021-07-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='table',
        ),
    ]
