# Generated by Django 3.2.5 on 2021-07-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
