# Generated by Django 3.2.5 on 2021-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='age',
        ),
        migrations.AddField(
            model_name='music',
            name='place',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
